use_frameworks!

target 'Lottie-Example' do
  pod 'lottie-ios', :git => 'https://github.com/Alex1989Wang/lottie-ios.git'

  target 'lottie-ios_Tests' do
    inherit! :search_paths

    
  end
end

target 'Lottie-Example-MacOS' do
  pod 'lottie-ios', :git => 'https://github.com/Alex1989Wang/lottie-ios.git'
end
